export const  RESET_GAME = 'RESET_GAME';
export const DECREASE_LIFE = 'DECREASE_LIFE';
export const INCREASE_LIFE = 'INCREASE_LIFE';
export const UPDATE_SCORE = 'UPDATE_SCORE';
export const UPDATE_BEST_SCORE = 'UPDATE_BEST_SCORE';
